server:
  port: 8090
spring:
  application:
    name: mall-coin
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 0
      logic-not-delete-value: 1
    enable-sql-runner: true