spring:
  application:
    name: mall-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  data:
    redis:
      database: 5
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 50000
  cloud:
    nacos:
      config:
        namespace: mall
        import-check:
          enabled: false
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
        group: mall-cloud
        enabled: true
        timeout: 50000
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: mall
    gateway:
      routes: # 路由配置
        - id: mall-auth-api # 路由ID，没有固定规则但要求唯一，建议配合服务名 mall-auth-api配置的Nacos注册中心的服务名称。
          uri: lb://mall-auth-api # 路由地址 允许三种配置 websocket方式，http方式，以及负载均衡方式(lb)
          order: 8001 # 路由顺序，数字越小优先级越高
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/auth/**
          filters: # 过滤器
            - StripPrefix=2 # 去掉前缀，数量为2，表示去掉第二个路径
        - id: mall-order-api # 路由ID，没有固定规则但要求唯一，建议配合服务名 mall-auth-api配置的Nacos注册中心的服务名称。
          uri: lb://mall-order-api # 路由地址 允许三种配置 websocket方式，http方式，以及负载均衡方式(lb)
          order: 8002 # 路由顺序，数字越小优先级越高
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/order/**
          filters: # 过滤器
            - StripPrefix=2 # 去掉前缀，数量为2，表示去掉第二个路径
        - id: product-service # 路由ID，没有固定规则但要求唯一，建议配合服务名 mall-auth-api配置的Nacos注册中心的服务名称。
          uri: lb://product-service # 路由地址 允许三种配置 websocket方式，http方式，以及负载均衡方式(lb)
          order: 8002 # 路由顺序，数字越小优先级越高
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/product/**
          filters: # 过滤器
            - StripPrefix=2 # 去掉前缀，数量为2，表示去掉第二个路径
        - id: mall-shoppingcart-api # 路由ID，没有固定规则但要求唯一，建议配合服务名 mall-auth-api配置的Nacos注册中心的服务名称。
          uri: lb://mall-shoppingcart-api # 路由地址 允许三种配置 websocket方式，http方式，以及负载均衡方式(lb)
          order: 8002 # 路由顺序，数字越小优先级越高
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/shoppingCart/**
          filters: # 过滤器
            - StripPrefix=2 # 去掉前缀，数量为2，表示去掉第二个路径
        - id: mall-ai-api # 路由ID，没有固定规则但要求唯一，建议配合服务名 mall-auth-api配置的Nacos注册中心的服务名称。
          uri: lb://mall-ai-api # 路由地址 允许三种配置 websocket方式，http方式，以及负载均衡方式(lb)
          order: 8002 # 路由顺序，数字越小优先级越高
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/ai/**
          filters: # 过滤器
            - StripPrefix=2 # 去掉前缀，数量为2，表示去掉第二个路径
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD}
      eager: true
  config:
    import: nacos:mall-gateway-dev.yaml
server:
  port: 8020

gateway:
  filter:
    noAuth: /api/auth/v1/web/user/code,/api/auth/v1/web/user/login
mall:
  mgt:
    tokenSecret: ${MALL_TOKEN_SECRET}